#!/bin/bash

consoleLog ()                                             
{                                                         
# Использование consoleLog "Hello World" [logfile]        
    echo '['$(date +'%d-%m-%Y %H:%M:%S')']: '$1 >> $2  
    if [ -n "$3" ]; then echo '['$(date +'%d-%m-%Y %H:%M:%S')']: '$1 >> $3; fi
}
